<?php

namespace cdemo;

$models = array(
    'Arctic Cat' => array(
        'Bearcat',
        'Bearcat 2000 LT ES',
        'Bearcat 200 XT ES',
        'Bearcat 3000 LT',
        'Bearcat 7000 XT',
        'Bearcat 7000 XT GS',
        'CFR',
        'CFR 1000',
        'CFR 800',
        'Cheetah',
        'Cheetah 400',
        'Cheetah 440',
        'Cheetah 5000',
        'F4',
        'F5',
        'F6',
        'F7',
        'F8',
        'King Cat',
        'King Cat 900',
        'King Cat 9000',
        'LYNX',
        'Lynx 292',
        'Lynx 300',
        'Lynx 340',
        'Lynx 570',
        'Lynx 2000',
        'Mountain Cat',
        'Mountain Cat 600',
        'Mountain Cat 800',
        'El Tigre',
        'LYNX 2000 ES',
        'LYNX 200 LT ES',
        'M7',
        'M 1000',
        'M 6000',
        'M 7000',
        'M 8000',
        'M 9000',
        'M 6000 SE ES',
        'M 6000 SNO PRO',
        'M 6000 SNO PRO ES',
        'M 8000 SNO PRO ES',
        'M 8000 SE ES',
        'M 8000 SNO PRO',
        'M 8000 LIMITED',
        'M 8000 LIMITED ES',
        'M 8000 MOUNTAIN CAT',
        'M 8000 HCR',
        'M 8000 SNO LIMITED',
        'M 8000 SNO LIMITED ES',
        'M 8000 MOUNTAIN CAT ES',
        'M 8000 MOUNTAIN CAT SPECIAL EDITION',
        'PANTERRA',
        'PANTERRA 3000',
        'PANTERRA 7000 LIMITED',
        'PANTERRA 7000 XT LIMITED',
        'POWDER EXTREME 600',
        'PROCLIMB',
        'PROCLIMB M 1100',
        'PROCLIMB M 800',
        'PROCLIMB XF 1100',
        'PROCLIMB XF 800',
        'PROCESS F 1100',
        'PROCESS F 800',
        'PROCESS XF 1100',
        'PROCESS XF 800',
        'PROWLER',
        'PROWLER 440',
        'PROWLER500 HDX',
        'PROWLER 500 XT',
        'PROWLER650',
        'PROWLER700',
        'PROWLER700 HDX',
        'PROWLER 700 XTX',
        'PROWLER 800',
        'SABERCAT',
        'SABERCAT 500',
        'SABERCAT 600',
        'SABERCAT 700',
        'Sno Pro 120',
        'Sno Pro 440',
        'Sno Pro F-10',
        'T 500',
        'T 570',
        'TBX',
        'TBX 650',
        'TBX 700',
        'XF 800',
        'XF 6000',
        'XF 7000',
        'XF 8000',
        'XF 9000',
        'XF 6000 CROSS COUNTRY LIMTIED ES',
        'XF 6000 CROSSTREK ES',
        'XF 6000 HIGH COUNTRY',
        'XF 6000 HIGH COUNTRY LIMITED ES',
        'XF 7000 CROSSTREK',
        'XF 7000 CROSSTOUR',
        'XF 8000 CROSSTREK ES',
        'XF 8000 HIGH COUNTRY',
        'XF 9000 CROSS COUNTRY LIMITED',
        'XF 9000 CROSSTREK',
        'XF 9000 HIGH COUNTRY LIMITED',
        'ZL 580',
        'ZR 600',
        'ZR 900',
        'ZR 5000',
        'ZR 6000',
        'ZR 7000',
        'ZR 8000',
        'ZR 9000',
        'ZR 3000 LXR',
        'ZR 4000 LXR',
        'ZR 4000 SNO PRO',
        'ZR 5000 LXR',
        'ZR 6000 LXR ES',
        'ZR 6000 SNO PRO ES',
        'ZR 6000 LIMITED ES',
        'ZR 6000 EL TIGRE ES',
        'ZR 6000 RR ES',
        'ZR 6000 RS',
        'ZR 7000 LXR',
        'ZR 7000 SNO PRO',
        'ZR 7000 LIMITED',
        'ZR 8000 LXR ES',
        'ZR 8000 SNO PRO ES',
        'ZR 8000 LIMITED ES',
        'ZR 8000 EL TIGRE ES',
        'ZR 8000 RR ES',
        'ZR 9000 LXR',
        'ZR 9000 SNO PRO',
        'ZR 9000 RR',
        'ZR 9000 THUNDERCAT',
        '50',
        '90',
        '150',
        'Sno Pro',
        'ZR 120',
    ),
    'Polaris' => array(
        '700',
        'APOLLO',
        'CENTURION',
        'CLASSIC',
        'CLASSIC 500',
        'CLASSIC 550',
        'CLASSIC 600',
        'CLASSIC 700',
        'CUTLASS',
        'EDGE',
        'EDGE 600',
        'EDGE X 600',
        'EDGE 800',
        'EDGE X 800',
        'FUSION',
        'FUSION 400',
        'FUSION 500',
        'FUSION 600',
        'FUSION 700',
        'FUSION 800',
        'FUSION 900',
        'FS',
        'FS IQ',
        'FST',
        'FST 750',
        'GALAXY',
        'GALAXY 340',
        'GALAXY 440',
        'GEMINI',
        'GEMINI 244',
        'GEMINI 250',
        'GEMINI 340',
        'INDY',
        '120 INDY',
        '600 INDY',
        '800 INDY',
        'INDY LITE DELUXE',
        '500 IQ',
        '550 IQ',
        '600 IQ',
        '700 IQ',
        '800 IQ',
        'IQR',
        'IQR 400',
        'IQR 440',
        'IQR 600',
        'IQR 800',
        'IQR 800 ES',
        'IQ CRUISER',
        'PRO-RMK',
        '800 PRO-RMK',
        'RMK',
        '600 RMK',
        '800 RMK',
        '800 RMK ASSULT',
        'RUSH',
        '600 RUSH',
        '600 RUSH PRO-S',
        '800 RUSH',
        'SPRINT',
        'SPRINT 340',
        'SHIFT',
        '550 SHIFT IQ',
        '600 SHIFT IQ',
        'SKS',
        'SKS 700',
        'SKS 800',
        'Startrak',
        'Startrak 750',
        'Startrak 800',
        'Startrak 900',
        'SuperSport',
        'SuperSport 440',
        'SuperSport 488',
        'SuperSport 550',
        '600 SWITCHBACK',
        '600 SWITCHBACK PRO_S',
        '800 SWITCHBACK',
        'SWITCHBACK',
        'SWITCHBACK 550',
        'SWITCHBACK 600',
        'SWITCHBACK 700',
        'SWITCHBACK 750',
        'SWITCHBACK 800',
        'SWITCHBACK 900',
        'TURBO DRAGON 700',
        'TURBO DRAGON 750',
        'TURBO DRAGON 800',
        'TX',
        'TX 340',
        'TX 440',
        'XC',
        'XC 120',
        'XC 340',
        'XC 400',
        'XC 440',
        'XC 500',
        'XC 600',
        'XC 700',
        'XC 800',
        'XC 900',
        'XCF 440',
        'XLT',
        'XLT 580 Triple',
        'XLT 600 Triple',
    ),
    'Yamaha' => array(
        'APEX',
        'APEX SE',
        'APEX LE',
        'APEX X-TX LE',
        'APEX X-TX',
        'MOUNTAIN',
        'MOUNTAIN MAX',
        'MOUNTAIN MAX 500',
        'MOUNTAIN MAX 600',
        'MOUNTAIN MAX 700',
        'MOUNTAIN MAX 800',
        'PHAZER',
        'PHAZER R-TX',
        'PHAZER X-TX',
        'PHAZER M-TX',
        'RS VECTOR X-TX LE',
        'RS VECTOR X-TX',
        'RS VECTOR',
        'RS VECTOR LE',
        'RS VECTOR L-TX',
        'RS VECTOR X-LE',
        'RS VIKING PROFFESSIONAL',
        'RS VENTURE',
        'RS VENTURE GT',
        'RS VENTURE TF',
        'RS VENTURE TF LE',
        'SIDEWINDER',
        'SIDEWINDER R-TX LE',
        'SIDEWINDER R-TX SE',
        'SIDEWINDER L-TX LE',
        'SIDEWINDER L-TX SE',
        'SIDEWINDER L-TX DX',
        'SIDEWINDER S-TX LDX',
        'SIDEWINDER X-TX LE 137',
        'SIDEWINDER X-TX LE 141',
        'SIDEWINDER X-TX SE 141',
        'SIDEWINDER B-TX LE 153',
        'SIDEWINDER B-TX SE 153',
        'SIDEWINDER M-TX SE 162',
        'SNOSCOOT',
        'SNOSPORT',
        'SRVIPER',
        'SRVIPER R-TX SE',
        'SRVIPER R-TX LE',
        'SRVIPER R-TX DX',
        'SRVIPER L-TX LE',
        'SRVIPER L-TX SE',
        'SRVIPER L-TX DX',
        'SRVIPER S-TX LDX 137',
        'SRVIPER S-TX LDX 146',
        'SRVIPER S-TX 137 DX',
        'SRVIPER S-TX 146 DX',
        'SRVIPER S-TX DX',
        'SRVIPER X-TX SE',
        'SRVIPER X-TX LE',
        'SRVIPER X-TX SLE',
        'SVIPER B-TX LE 153',
        'SRVIPER M-TX 141 SE',
        'SRVIPER M-TX 153',
        'SRVIPER M-TX 162',
        'SRVIPER M-TX SE 162',
        'SRVIPER M-TX SE 153',
        'SRVIPER M-TX LE 153',
        'SRVIPER M-TX LE 162',
        'SRX',
        'SRX120',
        'VENTURE MULTI-PURPOSE',
        'VK540',
        'VK PROFFESSIONAL II',
    ),
);

return $models;