<?php

namespace cdemo;

$models = array(
    'Acura' => array(
        'Integra',
        'NSX',
        'Vigor',
        'TL',
        'RL',
        'SLX',
        'CL',
        'MDX',
        'RSX',
        'TSX',
        'RDX',
        'ZDX',
        'NSX-T',
        'TL Series',
        'EL',
        'CSX',
        'TSX Sport Wagon',
        'ILX',
        'RLX',
        'TLX',
    ),
    'Alfa Romeo' => array(
        'Milano',
        'Spider',
        '164 Series',
        'Spider Veloce',
        'GTV-6',
        'Alfa Romeo',
        '4C',
        '4C Coupe',
        'Giulia',
        'Giulia Quadrifoglio',
        'Stelvio',
        '4C Spider',
    ),
    'AM General' => array(
        'Hummer',
    ),
    'American Motors Corporation' => array(
        'Eagle',
        'Concord',
        'Eagle 30 4WD',
        'Eagle 50 4WD',
        'Spirit',
        'Eagle 4WD',
        'Encore',
        'Sport Wagon',
        'Alliance',
    ),
    'Auston Martin' => array(
        'DB7 Vantage',
        'Vanquish',
        'DB7',
        'Vanquish S',
        'DB9',
        'Vantage',
        'DBS',
        'Rapide',
        'V8 Vantage',
        'V12 Vantage',
        'Virage',
        'Rapide S',
        'DB11',
    ),
    'Audi' => array(
        '5000S',
        '4000CS',
        '5000CS',
        'Coupe GT',
        '4000S',
        '90',
        '80',
        '100',
        '200',
        'Coupe Quattro',
        'V8 Quattro',
        'S4',
        'S6',
        'A6',
        'A4',
        'A8',
        'TT',
        'S8',
        'Allroad',
        'RS6',
        'A8 L',
        'A3',
        'RS 4',
        'Q7',
        'R8',
        'S5',
        'A5',
        'TTS',
        'Q5',
        '90 Series',
        '100 Series',
        'Cabriolet',
        'A6 Series',
        'A4 Series',
        'A8 Series',
        'S6 Series',
        'A7',
        'TT RS',
        '4000',
        '5000',
        'Coupe',
        'Quattro',
        '4000/GT Coupe',
        'Custom',
        'GT',
        'A4 Quattro Cabri',
        'RS 5',
        'S7',
        'RS5',
        'RS 7',
        'SQ5',
        'Q3',
        'S3',
        'A4 allroad',
        'A3 e-tron',
        'A5 Cabriolet',
        'A5 Coupe',
        'S5 Cabriolet',
        'S5 Coupe',
        'S8 plus',
        'TT Coupe',
        'TT Roadster',
        'A3 Sedan',
        'A3 Cabriolet',
        'A3 Sportback e-tron',
        'R8 Coupe',
        'R8 Spyder',
        'S4 Sedan',
        'A5 Sportback',
        'S5 Sportback',
        'TT RS Coupe',
        'RS 3 Sedan',
        'S3 Sedan',
        'RS 3',
        'TTS Coupe',
        'A4 Sedan',
        'RS 7 Sportback',
        'RS 7 Sportback Performance',
        'S7 Sportback',
        'A7 Sportback',
    ),
    'Bentley' => array(
        'Arnage',
        'Azure',
        'Continental Flying Spur',
        'Continental GT',
        'Brooklands',
        'Continental Supersports',
        'Mulsanne',
        'Continental',
        'Continental GT V8',
        'Continental GT Speed',
        'Flying Spur',
        'Continental GT V8 S',
        'Bentayga',
    ),
    'BMW' => array(
        '5 Series',
        '7 Series',
        '3 Series',
        '6 Series',
        '8 Series',
        '3-Series',
        '7-Series',
        '8-Series',
        'Z3',
        'X5',
        'Z8',
        'Z4',
        'X3',
        '1 Series',
        'X6',
        'M3',
        'M5',
        'M6',
        '5 Series Gran Turismo',
        'X5 M',
        'X6 M',
        '5-Series',
        'Z3-Series',
        'Z3 Series',
        'X5 Series',
        '1 Series M',
        'X1',
        '528 - 533 - 633 - 733',
        '320i',
        '318',
        '325e',
        '524 - 528 - 535 - 635 - 735',
        '325',
        '3 Series Gran Turismo',
        '4 Series',
        '2 Series',
        'i3',
        'M4',
        'X4',
        'i8',
        'X5 eDrive',
        'M2',
    ),
    'Buick' => array(
        'Skylark',
        'Regal',
        'Century',
        'Skyhawk',
        'LeSabre',
        'Riviera',
        'Electra',
        'Reatta',
        'Electra/Park Avenue',
        'Estate Wagon',
        'Roadmaster',
        'Park Avenue',
        'Rendezvous',
        'Rainier',
        'LaCrosse',
        'Terraza',
        'Lucerne',
        'Enclave',
        'Allure',
        'Verano',
        'Somerset Regal',
        'Encore',
        'Cascada',
        'Envision',
        'Regal Sportback',
        'Regal TourX',
    ),
    'Cadillac' => array(
        'Eldorado',
        'Brougham',
        'Seville',
        'Deville/Fleetwood',
        'Allante\'',
        'Fleetwood 75 Limo',
        'Cimarron',
        'Fleetwood d\'Elegance',
        'Deville',
        'Fleetwood Sixty Special',
        'Fleetwood',
        'Commercial Chassis',
        'Sixty Special',
        'Concours',
        'Catera',
        'Deville Professional',
        'd\'Elegance',
        'Escalade',
        'DeVille DHS',
        'DeVille DTS',
        'Escalade EXT',
        'CTS',
        'Escalade ESV',
        'XLR',
        'CTS-V',
        'SRX',
        'STS',
        'XLR-V',
        'DTS',
        'DTS Professional',
        'STS-V',
        'Escalade Hybrid',
        'CTS Sedan',
        'CTS Wagon',
        'CTS Coupe',
        'CTS-V Coupe',
        'CTS-V Sedan',
        'CTS-V Wagon',
        'Cimmaron',
        'Limousine',
        'Fleetwood FWD',
        'Fleetwood Brougham',
        'Fleetwood Seventy Five',
        'ATS',
        'XTS',
        'ELR',
        'ATS Coupe',
        'ATS Sedan',
        'ATS-V Coupe',
        'ATS-V Sedan',
        'CT6 Sedan',
        'XT5',
        'XT5 Crossover',
    ),
    'Chevrolet' => array(
        '1/2 Ton Pickups',
        'S-10 4WD',
        'Sport',
        'S-10 Blazer',
        '1 Ton Chassis-Cabs',
        'S-10 2WD',
        'Chevy',
        'EL Camino',
        'Suburban Diesel',
        '3/4 Ton Pickups',
        'Astro',
        'Blazer',
        'Suburban',
        'Camaro',
        'Caprice',
        'Cavalier',
        'Celebrity',
        'Chevette',
        'Corsica',
        'Corvette',
        'Monte Carlo',
        'Nova',
        'Spectrum',
        'Sprint',
        'Beretta',
        'S-10 Chassis Cab 2WD',
        'Chevy Sportvan',
        'S-10',
        '1 Ton Pickups',
        'Aluminum Step Van',
        'Hi-Cube Van',
        'Chevy Van',
        'Geo Spectrum',
        'Forward Control Chassis',
        'Steel Step Van',
        'Geo Metro',
        'Commercial/RV Cutaway Van',
        'Motor Home Chassis',
        'Astro Cargo',
        'Astro Passenger',
        'Geo Tracker',
        'Steel Value Van',
        'S/T Pickup',
        '1500 Work Pickups',
        '2500 Chassis-Cabs',
        '3500 Pickups',
        '1500 Pickups',
        'Lumina APV',
        '3500 Chassis-Cabs',
        'Lumina APV Cargo',
        '2500 Pickups',
        'Sport Van',
        'S/T Blazer',
        'Lumina',
        '3500 HD Chassis-Cabs',
        'V Blazer',
        'RV Cutaway Van',
        '1500 Sport Pickups',
        'Commercial Cutaway Van',
        'C/K 1500 Work',
        'C/K 3500 Crew Cab',
        'APV Cargo',
        'P Aluminum Step Van',
        'P Steel Step Van',
        'G Commercial Cutaway',
        'C/K 1500 Sport',
        'C/K 3500',
        'G RV Cutaway',
        'P Motor Home Chassis',
        'C/K 1500',
        'C/K 2500',
        'Astro Cargo Van',
        'P Forward Control Chassis',
        'K Blazer',
        'G Hi-Cube',
        'C 3500 HD',
        'P Commercial Cutaway',
        'P Motor Home Cutaway',
        'P Hi-Cube',
        'Lumina Cargo Van',
        'Caprice Classic',
        'Impala SS',
        'Lumina Passenger Van',
        'C/K 1500 LT',
        'Tahoe',
        'Classic G Commercial Cutaway',
        'Classic G RV Cutaway',
        'Classic Sportvan',
        'Classic Chevy Van',
        'Express Van',
        'P Rear Pusher M Home Chassis',
        'P Rear Pusher Chassis',
        'Camaro Police Pkg',
        'Lumina Police/Taxi Pkgs',
        'Caprice Police/Taxi Pkgs',
        'Venture',
        'Chevy Cargo Van',
        'Malibu',
        'Venture Cargo Van',
        'Venture Taxi Pkg',
        'Tahoe Police Special',
        'Express Commercial Cutaway',
        'Express RV Cutaway',
        'Silverado 1500',
        'Express Cargo Van',
        'Silverado 2500',
        'Tahoe Special Service',
        'C/K 2500 Crew Cab',
        'CF6B042',
        'CC6H042',
        'CF7B042',
        'CC7H042',
        'CF7B064',
        'CC7H064',
        'New Tahoe',
        'Impala',
        'Impala Police/Taxi Pkgs',
        'Silverado 3500',
        'W3S042 11,050 GVWR',
        'W3S042 12,000 GVWR',
        'W4S042 14,050 GVWR',
        'Silverado 1500HD',
        'W4S042 14,500 GVWR',
        'Silverado 2500HD',
        'W5S042 17,950 GVWR',
        'W5R042 18,000 GVWR',
        'W5R042 19,500 GVWR',
        'Avalanche',
        'W3S042 12,000 Reg Cab',
        'TrailBlazer',
        'W4S042 14,500 Reg Cab',
        'Tahoe Police',
        'W4S042 14,500 Crew Cab',
        'W5S042 17,950 Reg Cab',
        'W5S042 17,950 Crew Cab',
        'W3S042 12000 GVWR GAS REG',
        'CC4500',
        'W3S042 12000 GVWR DSL REG',
        'W4S042 14500 GVWR DSL REG',
        'CC5500',
        'W3S042i 12000 GVWR GAS RE',
        'SSR',
        'CC6500',
        'W4S042 14500 GVWR DSL CRW',
        'Express Passenger',
        'W4S042 14050 GVWR GAS REG',
        'Silverado SS',
        'W5S042 17950 GVWR DSL REG',
        'CC7500',
        'W5S042 17950 GVWR DSL CRW',
        'W4S042i 14500 GVWR GAS RE',
        'Tahoe Special Service Veh',
        'CC8500',
        'CC8500 Tandem',
        'W5R042 18000 GVWR DSL REG',
        'W5R042 19500 GVWR DSL REG',
        'Aveo',
        'W3S042 W3500 DSL REG',
        'CT6500',
        'W3S042 W3500 GAS REG',
        'Impala Police Pkg',
        'Colorado',
        'W4S042 W4500 DSL REG',
        'CT7500',
        'W4S042 W4500 DSL CRW',
        'CT8500',
        'W4S042 W4500 GAS REG',
        'W5S042 W5500 DSL REG',
        'CT8500 Tandem',
        'Malibu Maxx',
        'W5S042 W5500 DSL CRW',
        'Silverado 2500 Crew Cab',
        'Classic',
        'W5R042 WT5500 DSL REG',
        'Silverado 1500 Crew Cab',
        'Equinox',
        'Uplander Cargo Van',
        'Uplander',
        'Cobalt',
        'Silverado 1500 Hybrid',
        'Tahoe Police Vehicle',
        'W5R042 W5500 HD DSL REG',
        'HHR',
        'Silverado 3500 Classic',
        'Silverado 3500HD',
        'W4S042 W4500 HD GAS REG',
        'Silverado 1500 Classic',
        'Silverado 1500 Classic Hybrid',
        'W4S042 W4500 HD DSL REG',
        'W4S042 W4500 HD DSL CRW',
        'Silverado SS Classic',
        'Silverado 1500HD Classic',
        'Silverado 2500HD Classic',
        'W3500 GAS REG',
        'W3500 GAS CREW',
        'Malibu Classic',
        'W3500 DSL REG',
        'W3500 DSL REG LSD',
        'W4500 HD GAS REG',
        'Tahoe Hybrid',
        'Impala Police',
        'W4500 HD GAS CREW',
        'W4500 HD DSL REG MT',
        'W4500 HD DSL REG AT',
        'W4500 HD DSL CREW',
        'W5500 DSL REG MT',
        'W5500 DSL REG AT',
        'W5500 DSL CREW',
        'W5500 HD DSL REG MT',
        'W5500 HD DSL REG AT',
        'Traverse',
        'W4500 HD DSL REG MT LSD',
        'W4500 HD DSL REG AT LSD',
        'W4500 HD DSL CREW LSD',
        'W5500 DSL REG MT LSD',
        'W5500 DSL REG AT LSD',
        'W5500 DSL CREW LSD',
        'W5500 HD DSL REG MT LSD',
        'W5500 HD DSL REG AT LSD',
        'Malibu Hybrid',
        'Lumina Mini Van',
        'Sportvan',
        'Lumina Cargo Mini Van',
        'Tracker',
        'Metro',
        'Venture Passenger',
        'Express Cutaway',
        'Tahoe Z71',
        'TrailBlazer EXT',
        'Express Commercial',
        'Express Commrcl Cutaway',
        'Optra',
        'Optra 5',
        'Epica',
        'Optra Wgn',
        'Cruze',
        'Volt',
        'Caprice Police Patrol Vehicle',
        'Captiva Sport Fleet',
        'Sonic',
        'Orlando',
        'Prizm',
        'G Series Van',
        'P Series Van',
        'LUV',
        'Pickup',
        'Citation',
        'Van',
        'Citation II',
        'Astro Passenger Van',
        'K10 Blazer',
        '3/4 Ton Chassis-Cabs',
        'Cab & Chassis',
        'Crew Chassis',
        'S-10 Chassis Cab',
        '1500 Chassis-Cabs',
        'Spark',
        'Trax',
        'Corvette Stingray',
        'Impala Limited',
        'Impala Limited Police',
        'Spark EV',
        'SS',
        'City Express Cargo Van',
        'Silverado 3500HD Classic',
        'Silverado 2500HD (pre-Sept 2014)',
        'Silverado 3500HD (pre-Sept 2014)',
        'Silverado 2500HD Built After Aug 14',
        'Silverado 3500HD Built After Aug 14',
        'Cruze Limited',
        'Malibu Limited',
        '3500 Gas',
        '3500HD Diesel',
        '4500 Gas',
        '4500HD Diesel',
        '4500XD Diesel',
        '5500HD Diesel',
        '5500XD Diesel',
        'Bolt EV',
        '6500XD Diesel',
    ),
    'Chrysler' => array(
        'Lebaron',
        'New Yorker',
        'Fifth Avenue',
        'Lebaron GTS',
        'Conquest',
        'Imperial',
        'Town & Country',
        'New Yorker Fifth Avenue',
        'Salon',
        'New Yorker Landau',
        'TC',
        'New Yorker Salon',
        'Concorde',
        'LHS',
        'Cirrus',
        'Sebring',
        '300M',
        'PT Cruiser',
        'Pacifica',
        'Crossfire',
        '300',
        'Sebring Sdn',
        'Sebring Cpe',
        'Sebring Conv',
        'Town & Country SWB',
        'Town & Country LWB',
        'Aspen',
        'PT Cruiser Classic',
        'Intrepid',
        'Neon',
        'Intrepid Special Service',
        'Prowler',
        '200',
        'Voyager',
        'Cordoba',
        'Newport',
        'E Class',
        'Executive Sedan',
        'New Yorker E Class',
        'Laser',
        'Landau',
        'Pacifica Hybrid',
    ),
    'Deawoo' => array(
        'Lanos',
        'Nubira',
        'Leganza',
    ),
    'Daihatsu' => array(
        'Rocky',
        'Charade',
    ),
    'Datsun' => array(
        '210',
        '310',
        '510',
        '200SX',
        '280ZX',
        '720 Pickup',
        'B-210',
        '810',
        'Maxima',
        'Sentra',
        'Stanza',
        'Pulsar',
    ),
    'Dodge' => array(
        '600',
        'Colt',
        'Diplomat',
        'Shadow',
        'Mini Ram Van',
        'Ram Charger',
        'Vans',
        'Aries',
        'Colt Vista Wagon',
        'Lancer',
        'D100 & W100',
        'Raider',
        'Ram Wagon',
        'Caravan',
        'Daytona',
        'Omni/Charger',
        'Dakota',
        'Ram 50',
        'Trucks',
        'Aries America',
        'Dynasty',
        '3/4 Ton Trucks',
        '1 Ton Trucks',
        'Omni America',
        '1/2 Ton Trucks',
        'Caravan Cargo',
        'Spirit',
        'D150 & W150',
        'D350 & W350',
        'Colt DL/Vista Wagon',
        'Monaco',
        'D250 & W250',
        'Stealth',
        'Ram Van',
        'Viper',
        'Intrepid',
        'Dakota Chassis Cab',
        'Ram 1500',
        'Ram 2500 Chassis Cab',
        'Ram 2500',
        'Ram 3500 Chassis Cab',
        'Ram 3500',
        'Neon',
        'Stratus',
        'Avenger',
        'Dakota CNG',
        'Caravan CNG',
        'Ram Van CNG',
        'Ram Wagon CNG',
        'Ram 1500 CNG',
        'Ram 2500 CNG',
        'Ram BR2500',
        'Ram BR3500',
        'Ram BR2500 Chassis Cab',
        'Durango',
        'Intrepid Police',
        'Caravan C/V',
        'Sprinter Wagon',
        'Sprinter',
        'Ram SRT-10',
        'Magnum',
        'Stratus Cpe',
        'Stratus Sdn',
        'Charger',
        'Grand Caravan',
        'Grand Caravan C/V',
        'Nitro',
        'Caliber',
        'Ram 4500',
        'Ram 5500',
        'Challenger',
        'Journey',
        'Ram Wagons',
        'Ram BR1500',
        'Ram Vans',
        'Ram BR2500 CNG',
        'Ram BR3500 Chassis Cab',
        'SX 2.0',
        'D Series Pickup',
        'W Series Pickup',
        'D50 Pickup',
        'RD Pickup',
        'Mirada',
        'Omni',
        'St Regis',
        '400',
        'Rampage',
        'Pickup',
        'Van',
        'Ram D50 Pickup',
        'Conquest',
        'D/W Series Pickup',
        'Mini-Ram Van',
        'B Series Van/Wagon',
        'Dart',
        'SRT Viper',
    ),
    'Eagle' => array(
        'Medallion',
        'Premier',
        'Summit',
        'Talon',
        'Vision',
        'Summit Wagon',
        'Eagle',
    ),
    'Ferrari' => array(
        '360',
        '575M Maranello',
        '456M',
        'ENZO',
        '430',
        '612 Scaglietti',
        '599 GTB Fiorano',
        'California',
        '458 Italia',
        '599',
        'FF',
        'F12berlinetta',
        'LaFerrari',
        '488 GTB',
        'GTC4Lusso',
    ),
    'Fiat' => array(
        '500',
        'Brava',
        '124',
        'Strada',
        'X 1/9',
        '500e BATTERY ELECTRIC',
        '500L',
        '500c',
        '500e',
        '500X',
        '124 Spider',
        '500 Abarth',
    ),
    'Fisker' => array(
        'Karma',
    ),
    'Ford' => array(
        'Ltd Crown Victoria',
        'Tempo',
        'F-250',
        'Ranger S',
        'Bronco',
        'Explorer',
        'Crown Victoria',
        'F-150 Special',
        'F-350 Crew Cab',
        'Econoline Commercial Cutaway',
        'F-Super Duty Motorhome',
        'Crown Victoria Police Pkg',
        'F-Super Duty Chassis Cab',
        'Econoline Commercial Chassis',
        'F-Super Duty Commercial',
        'Taurus Police Pkg',
        'F-350 Chassis Cab',
        'Econoline RV Cutaway',
        'Aspire',
        'Windstar',
        'Contour',
        'Aerostar',
        'F-250 Crew Cab',
        'Windstar Cargo Van',
        'Windstar Wagon',
        'Expedition',
        'Aerostar Cargo Van',
        'F-150 Standard',
        'F-250 Standard',
        'F-250 HD',
        'F-250 HD Crew Cab',
        'Super Duty F-350 SRW',
        'Super Duty F-550 Motorhome',
        'Econoline Wagon',
        'Super Duty F-350 DRW',
        'F-150 Work Series',
        'Super Duty F-450',
        'Super Duty F-550',
        'F-800',
        'F-250 Work Series',
        'Super Duty F-250',
        'Focus',
        'Excursion',
        'Super Duty F-650',
        'Super Duty F-750',
        'Escape',
        'Explorer Sport',
        'Explorer Sport Trac',
        'F-150 SuperCrew',
        'Super Duty F-450 DRW',
        'Super Duty F-550 DRW',
        'Super Duty E-550 Cutaway',
        'Police Interceptor',
        'ZX2',
        'Super Duty E-350 DRW',
        'Super Duty E-450 DRW',
        'Super Duty E-550 DRW',
        'Freestar Cargo Van',
        'Freestar Wagon',
        'Super Duty F-650 Straight Frame',
        'Super Duty F-750 Straight Frame',
        'F-150 Heritage',
        'Super Duty F-750 Severe Service',
        'Super Duty F-650 Pro Loader',
        'GT',
        'Five Hundred',
        'Freestyle',
        'Low Cab Forward',
        'Fusion',
        'Expedition EL',
        'Edge',
        'Taurus X',
        'Flex',
        'Transit Connect Wagon',
        'Transit Connect',
        'Fiesta',
        'Super Duty F-53 Motorhome',
        'Super Duty F-59 Stripped Chassis',
        'F-150 Series Special',
        'F-150 Series',
        'F-250 Series',
        'F-Super Duty ChassisCab',
        'F-350 Series',
        'F-350 Series Crew Cab',
        'Econoline',
        'F-250 Series Crew Cab',
        'F-150 Series Standard',
        'F-250 HD Series',
        'F-250 HD Series Crew Cab',
        'F-250 Series Standard',
        'Econoline Commrcl Cutaway',
        'Econoline Commrcl Chassis',
        'Econoline Cutaway',
        'Escort ZX2',
        'Super Duty F-550 Mtrhome',
        'Freestar',
        'Escape Hybrid',
        'Expedition Max',
        'Super Duty F-250 SRW',
        'Super Duty F-650 Pro Loader Gas',
        'Super Duty F-650 Straight Frame Gas',
        'Focus Electric',
        'Courier Pickup',
        'E-Series Passenger Van',
        'E-Series Cargo Van',
        'Fairmont',
        'F-Series Pickup',
        'E-Series Cutaway',
        'Granada',
        'LTD',
        'Pickup',
        'Van',
        'Ranger Pickup',
        'Exp Sport Coupe',
        'Fairmont Futura',
        'Bronco 4WD',
        'Econoline/Club Wagon',
        'EXP',
        '1/2 Ton Trucks',
        '3/4 Ton Trucks',
        '1 Ton Trucks',
        'C-Max Energi',
        'C-Max Hybrid',
        'Sedan Police Interceptor',
        'Utility Police Interceptor',
        'Fusion Energi',
        'Fusion Plug-In Hybrid',
        'Transit Cargo Van',
        'Transit Chassis Cab',
        'Transit Cutaway',
        'Transit Wagon',
        'Super Duty F-650 Tractor',
        'Super Duty F-750 Straight Frame Gas',
        'Super Duty F-750 Tractor',
        'F-150',
        'Mustang',
        'Taurus',
        'E-Series Stripped Chassis',
        'Transit Connect Van',
        'Police Interceptor Utility',
        'F-53 Motorhome Stripped Chassis',
        'F-59 Commercial Stripped Chassis',
        'Transit Chassis',
        'Transit Van',
        'Police Interceptor Sedan',
        'Fusion Hybrid',
        'EcoSport',
        'Transit Passenger Wagon',
    ),
    'Freightliner' => array(
        'Sprinter Cargo Vans',
        'Sprinter Chassis-Cabs',
        'Sprinter Crew Vans',
        'Sprinter Passenger Vans',
        'Sprinter Cargo Van',
        'Sprinter Crew Van',
        'Sprinter Passenger Van',
        'Sprinter Cab Chassis',
    ),
    'Genesis' => array(
        'G80',
        'G90',
    ),
    'Geo' => array(
        'Tracker',
        'Metro',
        'Storm',
        'Prizm',
    ),
    'General Motors Corporation' => array(
        'S15 4WD',
        'Rally',
        'S15 Jimmy',
        '3/4 Ton Chassis-Cabs',
        'Safari',
        'Caballero',
        '1 Ton',
        'S15 2WD',
        'Vandura',
        'Jimmy',
        'S15',
        '1 Ton Fleetside Pickups',
        'S15 Chassis Cab 2WD',
        'Safari Cargo',
        'Magnavan',
        'Vandura Special/Rally Camper',
        '2500 HD Chassis-Cabs',
        '1500 Sierra Special',
        'Aluminum Value Van',
        'S/T Jimmy',
        'Rally Camper Special',
        'V Jimmy',
        'Vandura Special',
        'Sonoma',
        'Sierra 3500',
        'G Vandura Special',
        'Sierra 1500',
        'Sierra 2500',
        'G Magnavan',
        'Safari Passenger',
        'Sierra 1500 Sport',
        'Sierra 3500 Crew Cab',
        'P Aluminum Value Van',
        'P Steel Value Van',
        'Yukon',
        'Sierra 3500 HD',
        'Sierra 1500 Special',
        'G Rally Camper Special',
        'P Vandura Commercial Chassis',
        'P Magnavan',
        'P School Bus Chassis',
        'P Vandura School Bus Chassis',
        'P Vandura Motor Home Chassis',
        'Sierra 1500 SLT',
        'G Savana Special',
        'Savana Passenger',
        'Savana Cargo',
        'G Savana Camper Special',
        'Safari Cargo Van',
        'Savana Cargo Van',
        'Envoy',
        'Savana Special',
        'New Sierra 2500',
        'Savana Camper Special',
        'New Sierra 1500',
        'Sierra Classic 1500',
        'Denali',
        'School Bus Chassis',
        'Sierra 2500 Crew Cab',
        'TF6B042',
        'TC6H042',
        'Classic Sierra 2500',
        'TF7B042',
        'TC7H042',
        'TF7B064',
        'TC7H064',
        'Classic Sierra 3500',
        'Classic Sierra Crew Cab',
        'Classic Sierra 3500 HD',
        'Yukon XL',
        'F6B042',
        'F7B042',
        'F7B064',
        'Yukon Denali',
        'Sierra 1500HD',
        'Yukon XL Denali',
        'Sierra 2500HD',
        'Savana Cutaway',
        'Envoy XL',
        'Savana RV Cutaway',
        'TC4500',
        'TC5500',
        'TC6500',
        'Sierra Denali',
        'TC7500',
        'TC8500',
        'TC8500 Tandem',
        'TT6500',
        'Envoy XUV',
        'Canyon',
        'TT7500',
        'TT8500',
        'TT8500 Tandem',
        'Sierra 1500 Crew Cab',
        'Sierra 1500 Hybrid',
        'Sierra 3500 Classic',
        'Sierra 3500HD',
        'Sierra 1500 Classic',
        'Acadia',
        'Sierra 1500 Classic Hybrid',
        'Sierra Denali Classic',
        'Sierra 1500HD Classic',
        'Sierra 2500HD Classic',
        'Yukon Hybrid',
        'Yukon Hybrid Denali',
        'Terrain',
        'Savana Commercial Cutaway',
        'Suburban',
        'Forward Control Chassis',
        'Sierra Classic 2500',
        'Sierra Classic 3500',
        'TW35042 12,000 GVWR',
        'TW45042 14,500 GVWR',
        'TW55042 17,950 GVWR',
        'W3S042 12,000 Reg Cab',
        'W4S042 14,500 Reg Cab',
        'W4S042 14,500 Crew Cab',
        'W5S042 17,950 Reg Cab',
        'W5S042 17,950 Crew Cab',
        'W5R042 18,000 GVWR',
        'W5R042 19,500 GVWR',
        'W3S042 W3500 DSL REG',
        'W4S042 W4500 DSL REG',
        'W4S042 W4500 DSL CRW',
        'W5S042 W5500 DSL REG',
        'W5S042 W5500 DSL CRW',
        'W3S042 W3500 DSL REG',
        'W4S042 W4500 DSL REG',
        'W4S042 W4500 DSL CRW',
        'W5S042 W5500 DSL REG',
        'W5S042 W5500 DSL CRW',
        'W5R042 W5500 HD DSL REG',
        'W5R042 W5500 DSL REG',
        'W4S042 W4500 HD DSL REG',
        'W4S042 W4500 HD DSL CRW',
        'W3500 GAS REG',
        'W3500 DSL REG',
        'W3500 DSL REG LSD',
        'W4500 HD GAS REG',
        'W4500 HD DSL REG MT',
        'W4500 HD DSL REG AT',
        'W4500 HD DSL CREW',
        'W5500 DSL REG MT',
        'W5500 DSL REG AT',
        'W5500 DSL CREW',
        'W5500 HD DSL REG MT',
        'W5500 HD DSL REG AT',
        'W3500 GAS CREW',
        'W4500 HD GAS CREW',
        'W4500 HD DSL REG MT LSD',
        'W4500 HD DSL REG AT LSD',
        'W4500 HD DSL CREW LSD',
        'W5500 DSL REG MT LSD',
        'W5500 DSL REG AT LSD',
        'W5500 DSL CREW LSD',
        'W5500 HD DSL REG MT LSD',
        'W5500 HD DSL REG AT LSD',
        'W3S042 11,050 GVWR',
        'W3S042 12,000 GVWR',
        'W4S042 14,050 GVWR',
        'W4S042 14,500 GVWR',
        'W5S042 17,950 GVWR',
        'W3S042 12000 GVWR GAS REG',
        'W3S042 12000 GVWR DSL REG',
        'W4S042 14500 GVWR DSL REG',
        'W4S042 14500 GVWR DSL CRW',
        'W4S042 14050 GVWR GAS REG',
        'W5S042 17950 GVWR DSL REG',
        'W5S042 17950 GVWR DSL CRW',
        'W5R042 18000 GVWR DSL REG',
        'W5R042 19500 GVWR DSL REG',
        'W3S042i 12000 GVWR GAS RE',
        'W4S042i 14500 GVWR GAS RE',
        'W3S042 W3500 GAS REG',
        'W4S042 W4500 GAS REG',
        'W5R042 WT5500 DSL REG',
        'W4S042 W4500 HD GAS REG',
        'G Series Van',
        'P Series Van',
        'Pickup',
        'S-15',
        'Jimmy 4WD',
        'S15 Pickup',
        'Van',
        'Safari Passenger Van',
        'K15 Jimmy',
        '3/4 Ton Pickups',
        'Suburban Diesel',
        '1/2 Ton Pickups',
        '1 Ton Chassis-Cabs',
        '1 Ton Pickups',
        'Motor Home Chassis',
        'Commercial/RV Cutaway Van',
        'Aluminum Step Van',
        'Steel Step Van',
        '1500 Pickups',
        '3500 Pickups',
        'S/T Pickup',
        '3500 Chassis-Cabs',
        '2500 Pickups',
        'Steel Value Van',
        '2500 Chassis-Cabs',
        '3500 HD Chassis-Cabs',
        '1500 Sport Pickups',
        'P Forward Control Chassis',
        'P Motor Home Chassis',
        'Vandura Commercial Chassis',
        'G Hi-Cube',
        'G Commercial Cutaway',
        'P Value Van',
        'Sierra 3500HD Classic',
        'Sierra 2500HD (pre-Sept 2014)',
        'Sierra 3500HD (pre-Sept 2014)',
        'Sierra 3500HD AVF',
        'Sierra 2500HD Built After Aug 14',
        'Sierra 3500HD Built After Aug 14',
        'Sierra 2500HD available WiFi',
        'Sierra 3500HD available WiFi',
        'Acadia Limited',
    ),
    'Honda' => array(
        'Civic',
        'Prelude',
        'Accord',
        'CRX',
        'Wagovan',
        'Passport',
        'Accord Wgn',
        'Civic del Sol',
        'Accord Sdn',
        'Accord Cpe',
        'Odyssey',
        'CR-V',
        'Insight',
        'S2000',
        'Pilot',
        'Element',
        'Civic Cpe',
        'Civic Si',
        'Civic Sdn',
        'Civic Hybrid',
        'Accord Hybrid',
        'Ridgeline',
        'Fit',
        'Accord Crosstour',
        'Accord Coupe',
        'Accord Sedan',
        'Accord Wagon',
        'CR-Z',
        'Crosstour',
        'Accord Plug-in Hybrid',
        'Fit EV',
        'Civic Sedan',
        'Civic Coupe',
        'HR-V',
        'Civic Hatchback',
        'Clarity Fuel Cell',
    ),
    'Hummer' => array(
        'H1',
        'H2',
        'H3',
        'H3 SUV',
        'H3T',
    ),
    'Hyundai' => array(
        'Excel',
        'Sonata',
        'Scoupe',
        'Elantra',
        'Accent',
        'Tiburon',
        'Santa Fe',
        'XG300',
        'XG350',
        'Tucson',
        'Azera',
        'Entourage',
        'Veracruz',
        'Genesis',
        'Elantra Touring',
        'Genesis Coupe',
        'Genesis Sedan',
        'Equus',
        'Veloster',
        'Elantra Coupe',
        'Elantra GT',
        'Santa Fe Sport',
        'Sonata Hybrid',
        'Sonata Plug-In Hybrid',
        'Santa Fe XL',
        'G80',
        'G90',
        'IONIQ Electric',
        'IONIQ Hybrid',
    ),
    'Infinity' => array(
        'M30',
        'Q45',
        'G20',
        'J30',
        'I30',
        'QX4',
        'I35',
        'G35 Sedan',
        'G35 Coupe',
        'M45',
        'FX35',
        'FX45',
        'QX56',
        'M35',
        'G37 Coupe',
        'EX35',
        'G37 Convertible',
        'G37 Sedan',
        'FX50',
        'M37',
        'M56',
        'Q45t',
        'G25 Sedan',
        'M35h',
        'EX37',
        'FX37',
        'JX35',
        'Q50',
        'Q60 Convertible',
        'Q60 Coupe',
        'Q70',
        'Q70h',
        'QX50',
        'QX60',
        'QX70',
        'QX80',
        'Q40',
        'Q70L',
        'Q70 Hybrid',
        'Q50 Hybrid',
        'QX30',
        'Q60',
        'QX60 Hybrid',
    ),
    'Isuzu' => array(
        'Diesel Pickups',
        'Impulse',
        'Gas Pickups',
        'I-mark',
        'Pickup',
        'Trooper II',
        'Amigo',
        'Trooper',
        'Rodeo',
        'Stylus',
        'Hombre',
        'Oasis',
        'VehiCROSS',
        'Rodeo Sport',
        'Axiom',
        'Ascender',
        'FTR',
        'W3S042 NPR GAS REG',
        'FVR',
        'W3S042 NPR DSL REG',
        'FXR',
        'W4S042 NPR HD GAS REG',
        'FXR Tandem',
        'W4S042 NPR HD DSL REG',
        'W4S042 NPR HD DSL CRW',
        'W5S042 NQR DSL REG',
        'W5S042 NQR DSL CRW',
        'W5R042 FRR DSL REG',
        'HTR',
        'HVR',
        'HXR',
        'HXR Tandem',
        'W5R042 NRR DSL REG',
        'i-280',
        'i-350',
        'i-290',
        'i-370',
        'NPR GAS REG',
        'NPR GAS CREW',
        'NPR DSL REG',
        'NPR DSL REG LSD',
        'NPR HD GAS REG',
        'NPR HD GAS CREW',
        'NPR HD DSL REG MT',
        'NPR HD DSL REG AT',
        'NPR HD DSL CREW',
        'NQR DSL REG MT',
        'NQR DSL REG AT',
        'NQR DSL CREW',
        'NRR DSL REG MT',
        'NRR DSL REG AT',
        'NPR HD DSL REG MT LSD',
        'NPR HD DSL REG AT LSD',
        'NPR HD DSL CREW LSD',
        'NQR DSL REG MT LSD',
        'NQR DSL REG AT LSD',
        'NQR DSL CREW LSD',
        'NRR DSL REG MT LSD',
        'NRR DSL REG AT LSD',
        'NPR DSL REG AT ECO-MAX',
        'Commercial Van',
        'NPR DSL REG AT ECO-MAX LSD',
        'NPR XD DSL CREW',
        'NPR XD DSL CREW LSD',
        'NPR XD DSL REG AT',
        'NPR XD DSL REG AT LSD',
        'NPR DSL REG AT',
        'NPR DSL REG AT LSD',
    ),
    'Jaguar' => array(
        'XJS',
        'XJ Vanden Plas',
        'XJ',
        'XJ12',
        'XJS Convertible',
        'XJ Series Sedan',
        'XK8',
        'S-TYPE',
        'X-TYPE',
        'XK',
        'XF',
        'XJ Series',
        'XK Series',
        'XJ6',
        'XJS Coupe',
        'XJ6L',
        'XJS-C',
        'XJ-SC',
        'XJ-SC HE',
        'XJ Soverign',
        'XJRS',
        'F-TYPE',
        'F-PACE',
        'XE',
        'E-PACE',
    ),
    'Jeep' => array(
        'Grand Wagoneer',
        '4WD Trucks',
        'Wrangler',
        'Comanche',
        'Wagoneer',
        'Cherokee',
        'Wagoneer Limited',
        'Grand Cherokee',
        'Cherokee Right-Hand-Drive',
        'Cherokee Police',
        'Cherokee Police Prep',
        'Cherokee RH Drive',
        'Liberty',
        'Commander',
        'Patriot',
        'Compass',
        'Wrangler Unlimited',
        'YJ',
        'TJ',
        'Cherokee 4WD',
        'Pickup 4WD',
        'CJ 4WD',
        'Scrambler 4WD',
        'Wagoneer 4WD',
        'Comanche Pickup',
        'Renegade',
        'Patriot X',
        'Compass X',
    ),
    'Kia' => array(
        'Sephia',
        'Sportage',
        'Spectra',
        'Rio',
        'Optima',
        'Sedona',
        'Sorento',
        'Amanti',
        'Rondo',
        'Borrego',
        'Soul',
        'Forte',
        'Forte Koup',
        'Magentis',
        'Spectra5',
        'Forte 5-Door',
        'Optima Hybrid',
        'Cadenza',
        'K900',
        'Soul EV',
        'Rio 5-door',
        'Forte5',
        'Optima Plug-In Hybrid',
        'Niro',
    ),
    'Lamborghini' => array(
        'Murcielago',
        'Gallardo',
        'Aventador',
        'Huracan',
    ),
    'Land Rover' => array(
        'Range Rover',
        'Defender 110',
        'Defender 90',
        'Discovery',
        'Discovery Series II',
        'Freelander',
        'LR3',
        'Range Rover Sport',
        'LR2',
        'LR4',
        'Discovery II',
        'Range Rover Evoque',
        'Discovery SD',
        'Discovery Sport',
        'Range Rover Velar',
    ),
    'Lexus' => array(
        'LS 400',
        'ES 250',
        'SC 400',
        'ES 300',
        'SC 300',
        'GS 300',
        'LX 450',
        'ES 300 Luxury Sport Sdn',
        'SC 300 Luxury Sport Cpe',
        'GS 300 Luxury Perform Sdn',
        'SC 400 Luxury Sport Cpe',
        'LS 400 Luxury Sdn',
        'LX 450 Luxury Wagon',
        'GS 400 Luxury Perform Sdn',
        'LX 470 Luxury Wagon',
        'RX 300 Luxury SUV',
        'LX 470 Luxury SUV',
        'GS 400',
        'RX 300',
        'LX 470',
        'IS 300',
        'LS 430',
        'GS 430',
        'SC 430',
        'GX 470',
        'RX 330',
        'ES 330',
        'IS 250',
        'IS 350',
        'RX 400h',
        'ES 350',
        'GS 350',
        'GS 450h',
        'LS 460',
        'RX 350',
        'IS F',
        'GS 460',
        'LS 600h L',
        'LX 570',
        'IS 250C',
        'IS 350C',
        'HS 250h',
        'RX 450h',
        'GX 460',
        'LS 400 Luxury Sedan',
        'SC 400 Luxury Sport Coupe',
        'ES 300 Luxury Sport Sedan',
        'GS 300 Luxury Performance Sedan',
        'CT 200h',
        'LFA',
        'ES 300h',
        'RC F',
        'RC 350',
        'NX 200t',
        'NX 300h',
        'IS 200t',
        'GS 200t',
        'RC 200t',
        'RC 300',
        'GS F',
        'CT',
        'LX',
        'ES',
        'GX',
        'RX',
        'GS',
        'LS',
        'NX',
        'RC',
        'IS',
        'LC',
    ),
    'Lincoln' => array(
        'Mark VII',
        'Continental',
        'Town Car',
        'Mark VIII',
        'Navigator',
        'LS',
        'Blackwood',
        'Aviator',
        'Zephyr',
        'Mark LT',
        'MKZ',
        'MKX',
        'Navigator L',
        'MKS',
        'MKT',
        'Mark VI',
        'MKC',
    ),
    'Lotus' => array(
        'Esprit',
        'Elise',
        'Exige',
        'Evora',
        'Evora 400',
    ),
    'Maserati' => array(
        'Spyder',
        'GranSport',
        'Quattroporte',
        'GranTurismo',
        'GranTurismo Convertible',
        'Coupe',
        'Ghibli',
        'Levante',
    ),
    'Maybach' => array(
        '57',
        '62',
        '57S',
        '62S',
        'Landaulet',
        '57 Zeppelin',
        '62 Zeppelin',
    ),
    'Mazda' => array(
        'B2600 Pickup 4WD',
        'B2200 Pickup 2WD LX',
        '626',
        'B2600 Pickup 4WD SE-5',
        'B2600 Pickup 2WD LX',
        'B2200 Pickup 2WD',
        '323',
        'B2600 Pickup 4WD LX',
        'B2200 Pickup 2WD SE-5',
        'RX-7',
        'MX6',
        '929',
        'MPV',
        'MX-5 Miata',
        'B2600i Pickup 4WD',
        'Protege',
        'B2200/B2600i Pickup 2WD',
        'Navajo',
        'MX3',
        'B-Series 4WD Truck',
        'B-Series 2WD Truck',
        'Millenia',
        'MX5 Miata',
        'Tribute',
        'Protege5',
        'MAZDA6',
        'RX-8',
        'MAZDA3',
        'MAZDA5',
        'CX-7',
        'CX-9',
        'B-Series Truck',
        'RX7',
        '4WD Pickup',
        '2WD Pickup',
        'MPV Wagons',
        '4WD B-Series Pickup',
        '2WD B-Series Pickup',
        'MPV Wagon',
        'Tribute SUV',
        'B-Series Pickup',
        'MX-5',
        'MAZDA2',
        'GLC',
        'Pickup',
        'B2000 Pickup 2WD',
        'B2600 Pickup 2WD',
        'CX-5',
        'CX-3',
        'Mazda3 4-Door',
        'Mazda3 5-Door',
        'MX-5 RF',
        'MX-5 Miata RF',
        'Mazda3 Sport',
    ),
    'McLaren' => array(
        'MP4-12C',
        '650S',
        '675LT',
        '570S',
        '570GT',
    ),
    'Mercedes-Benz' => array(
        '420 Series',
        '190 Series',
        '300 Series',
        '560 Series',
        '260 Series',
        '400 Series',
        '600 Series',
        '500 Series',
        '200 Series',
        'E Class',
        'SL Class',
        'C Class',
        'S Class',
        'C-Class',
        'E-Class',
        'S-Class',
        'SL-Class',
        'SLK-Class',
        'CLK-Class',
        'CL-Class',
        'M-Class',
        'G-Class',
        'SLR McLaren',
        'CLS-Class',
        'R-Class',
        'GL-Class',
        'GLK-Class',
        'CLK Class',
        'SLK Class',
        'M Class',
        'CL Class',
        'B-Class',
        'Sprinter Cargo Vans',
        'Sprinter Passenger Vans',
        'Sprinter Chassis-Cabs',
        'SLS AMG',
        'Sprinter Crew Vans',
        '240 Series',
        '280 Series',
        '380 Series',
        'SLS AMG GT',
        'CLA-Class',
        'SLS AMG Black Series',
        'GLA-Class',
        'AMG GT',
        'GLE-Class',
        'Metris Cargo Van',
        'Metris Passenger Van',
        'GLC-Class',
        'CLA',
        'CLS',
        'GL',
        'GLA',
        'GLC',
        'GLE',
        'SL',
        'SLK',
        'GLS',
        'SLC',
        'Sprinter Cargo Van',
        'Sprinter Cab Chassis',
        'Sprinter Crew Van',
        'Sprinter Passenger Van',
    ),
    'Mercury' => array(
        'Grand Marquis',
        'Sable',
        'Cougar',
        'Tracer',
        'Lynx',
        'Topaz',
        'Capri',
        'Villager Van',
        'Villager Wagon',
        'Mystique',
        'Villager Wgn',
        'Mountaineer',
        'Villager',
        'Marauder',
        'Monterey',
        'Montego',
        'Mariner',
        'Milan',
        'Marquis',
        'Zephyr',
        'LN7',
    ),
    'Mekur' => array(
        'Scorpio',
        'XR4Ti',
    ),
    'MINI' => array(
        'Cooper Hardtop',
        'Cooper Convertible',
        'Cooper Clubman',
        'Cooper Countryman',
        'Cooper Coupe',
        'Cooper Roadster',
        'Cooper Paceman',
        'Cooper Clubvan',
        '5 Door',
        'Cooper Hardtop 4 Door',
        'Cooper Hardtop 5 Door',
        'Convertible',
        'Clubman',
        'Hardtop 2 Door',
        'Hardtop 4 Door',
        'Countryman',
        '3 Door',
    ),
    'Mitsubishi' => array(
        'Montero',
        'Wagon',
        'Starion',
        'Galant',
        '4WD Pickups',
        'Van',
        'Precis',
        'Cordia',
        '2WD Pickups',
        'Tredia',
        'Mirage',
        'Montero 4WD',
        'Sigma',
        'Mighty Max',
        'Eclipse',
        '3000GT',
        'Diamante',
        'Expo LRV',
        'Expo',
        'Pickups',
        'Montero Sport',
        'Outlander',
        'Endeavor',
        'Lancer',
        'Outlander Sport',
        'RVR',
        'i-MiEV',
        'Raider',
        'Lancer Evolution',
        'Lancer Sportback',
        'Montero 2WD',
        'Pickup',
        'Mirage G4',
    ),
    'Nissan' => array(
        'Maxima',
        'Stanza',
        'King Cab 2WD',
        'Long Bed 4WD',
        'Regular Bed 4WD',
        '200SX',
        'Pulsar NX',
        'Cab & Chassis',
        'King Cab 4WD',
        'Pathfinder',
        '300ZX',
        'Sentra',
        'Heavy Duty',
        'Long Bed 2WD',
        'Regular Bed 2WD',
        'Hardbody 4WD',
        'Hardbody King Cab 4WD',
        'Hardbody',
        '240SX',
        'Hardbody King Cab 2WD',
        'Axxess',
        'Hardbody 2WD',
        'Trucks 4WD',
        'Trucks 2WD',
        'NX',
        'Altima',
        'Quest',
        'Frontier 2WD',
        'Frontier 4WD',
        'Xterra',
        '350Z',
        'Murano',
        'Pathfinder Armada',
        'Titan',
        'Armada',
        'Frontier',
        'Versa',
        'Titan (2008.5)',
        'Rogue',
        '370Z',
        'GT-R',
        'cube',
        'X-Trail',
        'LEAF',
        'JUKE',
        'Murano CrossCabriolet',
        'NV',
        'Pickup',
        '280ZX',
        'Pulsar',
        'Pickup (1986.5)',
        'Van',
        'NV Fleet',
        'NVP',
        'NV200',
        'Rogue Select',
        'Versa Note',
        'NV200 Taxi',
        'Micra',
        'Titan XD',
        'NV200 Compact Cargo',
        'Versa Sedan',
        'NV Passenger',
        'NV Cargo',
        'Rogue Sport',
        '370Z Coupe',
        '370Z Roadster',
        'Qashqai',
    ),
    'Oldsmobile' => array(
        '98',
        'Cutlass Supreme',
        'Calais',
        'Firenza',
        'Cutlass Ciera',
        'Toronado',
        'Delta 88',
        'Custom Cruiser',
        'Cutlass Calais',
        'Touring Sedan',
        '98 Regency',
        'Silhouette',
        '88 Royale',
        'Bravada',
        'Cutlass Ciera/Cruiser',
        'Achieva',
        'Ciera',
        '98 Regency Elite',
        'Aurora',
        '88',
        'Cutlass',
        'LSS',
        'Regency',
        'Intrigue',
        'Alero',
        'Eighty Eight',
        'Omega',
        'Delta',
    ),
    'Panoz' => array(
        'Esperante',
    ),
    'Peugeot' => array(
        '505',
        '505 2.2L',
        '405',
        '505 2.8L V6',
        '504 Series',
        '505 Series',
        '604 Series',
    ),
    'Plymouth' => array(
        'Reliant',
        'Caravelle',
        'Voyager',
        'Horizon',
        'Sundance',
        'Gran Fury',
        'Acclaim',
        'Reliant America',
        'Horizon America',
        'Laser',
        'Breeze',
        'Voyager CNG',
        'Prowler',
        'Colt',
        'Colt Vista Wagon',
        'Neon',
        'Champ',
        'Arrow Pickup',
        'Trailduster',
        'Voyager Van',
        'Sapporo',
        'Turismo',
        'Scamp',
        'Conquest',
    ),
    'Pontiac' => array(
        'Grand Am',
        'Bonneville',
        'Lemans',
        'Firebird',
        '6000',
        'Sunbird',
        'Grand Prix',
        'Fiero',
        '1000',
        'Trans Sport',
        'Sunfire',
        'Montana',
        'Aztek',
        'Vibe',
        'GTO',
        'G6',
        'Montana SV6',
        'Solstice',
        'Torrent',
        'G5',
        'G8',
        'G3',
        'Firefly',
        'Sunrunner',
        'Wave',
        'Pursuit',
        'G5 Pursuit',
        'G3 Wave',
        'Catalina',
        'Grand Lemans',
        'Phoenix',
        'T1000',
        'J2000',
        'Parisienne',
        '2000 Sunbird',
        'Safari',
        'T-1000',
    ),
    'Porsche' => array(
        '924',
        '944',
        '911 Carrera',
        '928 S4',
        '964',
        '928',
        '944 S2',
        '911 Turbo',
        '968',
        '911 America Roadster',
        '911 Speedster',
        '911 Carrera 4',
        'Boxster',
        'Cayenne',
        'Carrera GT',
        'Cayman',
        'Panamera',
        '911',
        '928S',
        '924S',
        '918 Spyder',
        'Macan',
        '718 Boxster',
        '718 Cayman',
    ),
    'Ram' => array(
        '3500',
        '4500',
        '5500',
        'Dakota',
        '1500',
        '2500',
        'Cargo Van',
        'ProMaster',
        'ProMaster City',
        'ProMaster City Wagon',
        'ProMaster City Cargo Van',
        'ProMaster Cargo Van',
        'ProMaster Chassis Cab',
        'ProMaster Cutaway',
        'ProMaster Window Van',
        '5500 Chassis Cab',
        '3500 Chassis Cab',
        '4500 Chassis Cab',
        '3500 Chassis',
        '4500 Chassis',
        '5500 Chassis',
    ),
    'Renault' => array(
        '18i',
        'Le Car',
        'Fuego',
        'Alliance',
        '18I Series',
        'Encore',
        'Sport Wagon',
        'R18',
    ),
    'Rolls-Royce' => array(
        'Silver Seraph',
        'Park Ward',
        'Corniche',
        'Phantom',
        'Phantom Drophead Coupe',
        'Phantom Coupe',
        'Phantom Ghost',
        'Ghost',
        'Wraith',
        'Dawn',
    ),
    'SAAB' => array(
        '9000S',
        '900',
        '9000 Turbo',
        '900S',
        '900 Turbo',
        '9000',
        '42981',
        '42983',
        '9-2X',
        '9-7X',
        '9-4X',
        '900 Turbo Sedan',
        '900 Sedan',
    ),
    'Saturn' => array(
        'SL',
        'SC',
        'SW',
        '2dr Coupe',
        'SC 2dr',
        'SC 3dr',
        'SW RHD',
        'LW',
        'VUE',
        'Ion',
        'L-Series',
        'Relay',
        'Sky',
        'Aura',
        'Outlook',
        'Astra',
        'Aura Hybrid',
        'VUE Hybrid',
        '4dr Sedan',
        '4dr Wagon',
        '3dr Coupe',
        'SL 4dr Sedan',
        'SW 4dr Wagon',
        'SC 3dr Coupe',
        'LS 4dr Sedan',
        'LW 4dr Wagon',
        'VUE 4dr SUV',
        'Ion Sedan',
        'LS',
        'Ion Coupe',
        'Ion Quad Coupe',
        'L Series Sedan',
        'L Series Wagon',
    ),
    'Scion' => array(
        'xA',
        'xB',
        'xD',
        'tC',
        'iQ',
        'FR-S',
        'iM',
        'iA',
    ),
    'Smart' => array(
        'fortwo',
        'Lanos',
        'Nubira',
        'Leganza',
        'fortwo electric drive',
    ),
    'Spyker' => array(
        'C8 Aileron',
    ),
    'Sterling' => array(
        'Sterling',
    ),
    'Subaru' => array(
        '3 Dr',
        'Brat 4WD',
        'Justy',
        '4 Dr',
        'XT Coupe',
        'Hatchback',
        'Touring Wagon',
        'Loyale',
        'Legacy Sedan',
        'Justy GL',
        'Legacy Wagon',
        'SVX',
        'Impreza',
        'Impreza Wagon',
        'Impreza Sedan',
        'Impreza Coupe',
        'Forester',
        'Baja',
        'Impreza Sedan (Natl)',
        'Impreza Wagon (Natl)',
        'Impreza Sedan (NY/NJ)',
        'Forester (Natl)',
        'Legacy Sedan (Natl)',
        'Impreza Wagon (NY/NJ)',
        'Legacy Wagon (Natl)',
        'Legacy Sedan (NY/NJ)',
        'Forester (NY/NJ)',
        'Legacy Wagon (NY/NJ)',
        'Baja (Natl)',
        'B9 Tribeca',
        'Legacy (Natl)',
        'Outback (Natl)',
        'Tribeca (Natl)',
        'Legacy (NY/NJ)',
        'Outback (NY/NJ)',
        'Tribeca (NY/NJ)',
        'Impreza Sedan WRX',
        'Legacy',
        'Outback',
        'Impreza Wagon WRX',
        'Tribeca',
        'Impreza WRX',
        'Brat',
        'DL',
        'GL',
        'GLF',
        'Standard',
        'Std/DL',
        'RX',
        'GL10',
        'Wagon',
        'BRZ',
        'XV Crosstrek',
        'WRX',
        'XV Crosstrek Hybrid',
        'WRX STI',
        'Crosstrek',
        'Crosstrek Hybrid',
    ),
    'Suzuki' => array(
        'Samurai',
        'Sidekick',
        'Swift',
        'Esteem',
        'X-90',
        'Vitara',
        'Grand Vitara',
        'XL-7',
        'Aerio',
        'Forenza',
        'Verona',
        'Vitara V6',
        'Reno',
        'SX4',
        'XL7',
        'Equator',
        'Kizashi',
        'Swift+',
        'SX4 Sdn',
        'SX4 Fstbk',
        'SX4 Hatchback',
        'SX4 Sedan',
        'Jimny 4WD',
        'Samurai 4WD',
    ),
    'Tesla' => array(
        'Roadster',
        'Roadster 2.5',
        'Roadster Sport 2.5',
        'Model S',
        'Model X',
    ),
    'Toyota' => array(
        'SR5 Trucks 4WD',
        'Std Bed Trucks 4WD',
        'Corolla',
        'MR2',
        'Commercial Chassis-Cabs',
        'Camper Cab/Chassis',
        'Long Bed Trucks',
        'SR5 Xtracab Trucks',
        'Xtracab Trucks',
        'Camry',
        'Supra',
        'Cargo Vans',
        'Passenger Vans',
        'Std Bed Trucks',
        'Celica',
        'Cressida',
        'Tercel',
        '4Runner',
        'Land Cruiser',
        '4Runner SR5',
        'Previa',
        'Chassis-Cabs',
        'Paseo',
        'T100',
        'Tacoma',
        'Avalon',
        'RAV4',
        'Sienna',
        'Camry Solara',
        'Echo',
        'Tundra',
        'MR2 Spyder',
        'Prius',
        'Highlander',
        'Sequoia',
        'Matrix',
        'Highlander Hybrid',
        'Yaris',
        'FJ Cruiser',
        'Camry Hybrid',
        'Tundra 2WD Truck',
        'Tundra 4WD Truck',
        'Venza',
        '2WD Compact Trucks',
        '4WD Compact Trucks',
        'T100 Trucks',
        '2WD Compact Pickups',
        '4WD Compact Pickups',
        '4Runner SR5 Utilities',
        'T100 Pickups',
        'Tacoma Pickups',
        'Prius V',
        'Prius Plug In',
        'Prius c',
        'Pickup',
        'Starlet',
        'Corona',
        'Pickup & Landcruiser',
        'Van Wagon',
        '4runner 4WD',
        '2WD Pickups',
        'Vans',
        '4WD Pickups',
        'Prius Plug-In',
        'Avalon Hybrid',
        'RAV4 EV',
        'RAV4 Hybrid',
        'Mirai',
        'Tundra 2WD',
        'Tundra 4WD',
        '86',
        'Corolla iM',
        'Yaris iA',
        'Prius Prime',
        'C-HR',
        'Yaris Hatchback',
    ),
    'Volkswagen' => array(
        'Quantum',
        'Golf',
        'Vanagon',
        'Jetta',
        'Fox',
        'Scirocco',
        'GTI',
        'Cabriolet',
        'Corrado',
        'Passat',
        'Jetta III',
        'EuroVan',
        'Cabrio',
        'GTI VR6',
        'New Beetle',
        'New Golf',
        'New Jetta',
        'New GTI',
        'New Cabrio',
        'New Passat',
        'Jetta Sedan',
        'Jetta Wagon',
        'New Beetle Coupe',
        'New Beetle Convertible',
        'Touareg',
        'Passat Sedan',
        'Passat Wagon',
        'Phaeton',
        'R32',
        'Jetta Sedan A5',
        'Rabbit',
        'Eos',
        'GLI',
        'Touareg 2',
        'Jetta SportWagen',
        'CC',
        'Tiguan',
        'Routan',
        'Golf III',
        'Golf City',
        'Jetta City',
        'City Golf',
        'City Jetta',
        'Passat CC',
        'Golf GTI',
        'Golf Wagon',
        'Beetle',
        'Golf R',
        'Jetta GLI',
        'Vanagon/Campmobile',
        'Dasher',
        'Pickup',
        'Cabriolet/GTI',
        'Beetle Convertible',
        'Beetle Coupe',
        'e-Golf',
        'Golf SportWagen',
        'Golf Sportwagon',
        'Golf Alltrack',
        'Atlas',
    ),
    'Volvo' => array(
        '240 DL',
        '740',
        '780',
        '240 GL',
        '760',
        '740 GLE',
        '240',
        '760 GLE',
        'Coupe',
        '940',
        '850',
        '960',
        'S70',
        'V70',
        'S90',
        'V90',
        'C70',
        'S80',
        'S40',
        'V40',
        'S60',
        'XC90',
        'V50',
        'XC70',
        'C30',
        'XC60',
        '800 Series',
        '900 Series',
        '850 Series',
        '960 Series',
        'S70 Series Sedan',
        'V70 Series Wagon',
        'S90 Series Sedan',
        'V90 Series Wagon',
        'C70 Series',
        'S80 Series Sedan',
        '260',
        'DL',
        'GL',
        'GLE',
        '740/760',
        '900',
        '244',
        'V60',
        'V60 Cross Country',
        'S60 Inscription',
        'S60 Cross Country',
        'XC90 Hybrid',
        'V90 Cross Country',
    ),
    'Yugo' => array(
        'Yugo',
    ),
);

return $models;
