<?php

namespace cdemo;

$models = array(
    'Arctic Cat' => array(
        '250',
        '280',
        '350',
        '366',
        '371',
        '425',
        '450',
        '493',
        '90 Dvx',
        '250 Dvx',
        '400 Dvx',
        '366 SE',
        '450 H1',
        '400 H1 TRV',
        '450 Efi',
        'XC 450',
        '550 S',
        '550 H1 Efi Le',
        'ALTERRA',
        'ALTERRA 90',
        'ALTERRA 300',
        'ALTERRA 400',
        'ALTERRA 500',
        'Alterra Trv 400',
        'Alterra Trv 450',
        'Alterra Trv 500',
        'Alterra Trv 550',
        'Alterra Trv 550 Curiser',
        'Alterra Trv 550 Gt',
        'Alterra Trv 650',
        'Alterra Trv 700',
        'Alterra Trv 700 XT',
        'Alterra Trv 700 XT EPS',
        'Alterra Trv 700 Gt',
        'Alterra Trv 700 H1 Efi Curiser',
        'Alterra Trv 700 S Gt',
        'Alterra Trv 1000',
        'Alterra Trv 1000 XT',
        'HDX',
        'HDX 500 XT',
        'HDX 700 CREW XT',
        'HDX 700 XT EPS',
        'PROWLER',
        'PROWLER 500',
        'PROWLER 700 XT EPS',
        'PROWLER 1000 XT EPS',
        'WILDCAT',
        'WILDCAT TRAIL LIMITED EPS',
        'WILDCAT TRAIL XT EPS',
        'WILDCAT TRAIL',
        'WILDCAT SPORT LIMITED EPS',
        'WILDCAT SPORT XT EPS',
        'WILDCAT 4X',
        'WILDCAT X LIMITED',
        '650',
        '700',
        '700 S LTD',
        '700 Super Duty',
        'TBX 700',
        '90',
        'DVX',
        'DVX 90',
        'DVX 200',
        'DVX 250',
        'DVX 300',
        'DVX 400',
        'Mud Pro',
        'Mud Pro 650h1',
        'Mud Pro 700h1',
        'Mudpro 1000',
        'Mudpro 1000 LIMITED EPS',
        'Mudpro 650',
        'Mudpro 700',
        'Mudpro 700 LIMITED EPS',
        'Muscle Cat',
        'Muscle Cat 700h1',
        'Other',
        'Thundercat',
        'Thundercat 1000 H2',
        'Thundercat 1000 H2 Le',
        'Trail Cat',
        '150',
        'Work Cat',
        'Work Cat 550',
        'XR',
        'XR 500',
        'XR 700',
    ),
    'Bennche' => array(
        'Bighorn',
        'Bighorn 400',
        'Bighorn 500',
        'Bighorn 700',
        'Bighorn 700X Crew',
        'Cowboy',
        'Cowboy 400',
        'Cowboy 450',
        'Cowboy 500',
        'Cowboy 700',
        'Cowboy 1000',
        'Gray Wolf',
        'Gray Wolf 500',
        'Gray Wolf 700',
        'Spire',
        'Spire 250',
        'Spire 800',
        'Spire 1000',
        'Spire 1000X',
        'EV60',
        'Other',
    ),
    'Bobcat' => array(
        '2200',
        '3400',
        'Other',
    ),
    'Bombardier' => array(
        'Other',
    ),
    'Can-Am / BRP' => array(
        'COMMANDER',
        'COMMANDER DPS',
        'COMMANDER XT',
        'COMMANDER XT-P',
        'COMMANDER LIMITED',
        'COMMANDER MOSSY OAK HUNTING EDITION',
        'COMMANDER MAX DPS',
        'COMMANDER MAX XT',
        'COMMANDER MAX LIMITED',
        'DEFENDER',
        'DEFENDER DPS',
        'DEFENDER XT',
        'DEFENDER XT CAB',
        'DEFENDER MOSSY OAK HUNTING',
        'MAVERICK',
        'MAVERICK XC',
        'MAVERICK XC DPS',
        'MAVERICK X XC',
        'MAVERICK DPS',
        'MAVERICK TURBO',
        'MAVERICK MAX DPS',
        'MAVERICK MAX TURBO',
        'MAVERICK MAX X DS TURBO',
        'MAVERICK MAX X RS TURBO',
        'MAVERICK X MR',
        'MAVERICK MAX X MR',
        'MAVERICK X3',
        'OUTLANDER',
        'OUTLANDER 450',
        'OUTLANDER 570',
        'OUTLANDER XT',
        'OUTLANDER XT 570',
        'OUTLANDER XT 650',
        'OUTLANDER XT 850',
        'OUTLANDER XT 1000',
        'OUTLANDER XT 1000R',
        'OUTLANDER MAX',
        'OUTLANDER MAX DPS 450',
        'OUTLANDER MAX XT 570',
        'OUTLANDER X MR 570',
        'Other',
    ),
    'Case IH' => array(
        'Scout',
        'Other',
    ),
    'CFMOTO' => array(
        'CFORCE',
        'CFORCE 400 HO',
        'CFORCE 500 HO',
        'CFORCE 800EPS LX',
        'UFORCE 500 HO',
        'UFORCE 800 EPS LX',
        'ZFORCE',
        'ZFORCE 500 HO',
        'ZFORCE 800EPD/TRAIL',
        'ZFORCE 800EX / EPS',
    ),
    'Cub Cadet' => array(
        'Challenger',
        'Challenger 400',
        'Challenger 400 LX',
        'Challenger 500',
        'Challenger 700',
        'Challenger 750 Crew',
        'Volunteer',
        'Volunteer 4X4 EFI',
        'Volunteer WT CAB',
    ),
    'E-Ton' => array(
        'Rascal',
        'Rover',
        'Vector',
        'Viper RXL 50M',
        'Viper RXL 70',
        'Viper RX4 70 4-Stroke',
        'Viper RX4 70 Mini 4-S',
        'Viper RX4 70 Silver 4- Stroke',
        'Yukon',
    ),
    'Hisun' => array(
        'AXIS 110',
        'FORGE',
        'FORGE 110',
        'FORGE 250',
        'FORGE 400',
        'FORGE 500',
        'FORGE 700',
        'HS 400',
        'HS 500',
        'HS 700',
        'HS 750 CREW',
        'SECTOR',
        'SECTOR 250',
        'SECTOR 450',
        'SECTOR 550',
        'SECTOR 750',
        'SECTOR 750 CREW',
        'SECTOR 1000',
        'SECTOR 1000 CREW',
        'STRIKE',
        'STRIKE 250',
        'STRIKE 550',
        'STRIKE 800',
        'STRIKE 900',
        'STRIKE 1000',
        'STRIKE 1000 CREW',
        'TACTIC',
        'TACTIC 450 2-UP',
        'TACTIC 550 2-UP',
        'TACTIC 750 2-UP',
        'TACTIC 800',
        'TACTIC 1000',
        'PULSE GOLF CART',
        'SECTOR E1',
    ),
    'Honda' => array(
        'FOREMAN',
        'FOREMAN RUBICON',
        'FOREMAN 500',
        'FOREMAN 500 ES SPS',
        'PIONEER',
        'PIONEER 500',
        'PIONEER 700 Delux',
        'PIONEER 700 -4',
        'PIONEER 1000',
        'PIONEER 1000-5',
        'RANCHER',
        'RECON',
        'RINCON',
        'RINCON 680 AT IRS',
        'RUBICON 500',
        'RUBICON 500 IRS',
        'RUBICON 500 DCT',
        'RUBICON 500 DCT IRS EPS',
        'RUBICON 500 Deluxe DCT IRS EPS',
        'TRX',
        'TRX 90X',
        'TRX 250X',
        'TRX 400X',
        'TRX 450R',
        'TRX 420 DCT IRS EPS',
        'TRX 420 EPS',
        'TRX 520',
    ),
    'Hyosung' => array(
        'TE450S',
    ),
    'John Deere' => array(
        'M-Gator',
        'M-Gator A1',
        'M-Gator A3',
        'M-Gator A3-T',
        'RSX860i',
        'RSX850i',
        'RSX850i SPORT',
        'RSX850i TRAIL',
        'TE',
        'TS',
        'TX',
        'XUC550',
        'XUV550 S4',
        'XUV560',
        'XUV560 S$',
        'XUV590i',
        'XUV590I S4',
        'XUV625i',
        'XUV825i',
        'XUV825i Special Edition',
        'XUV825i S4',
        'XUV855D',
        'XUV855D S4',
    ),
    'Kawasaki' => array(
        'Bayou',
        'Brute Force',
        'Brute Force 300',
        'Brute Force 750',
        'Brute Force 750 CAMO',
        'Brute Force 750 CAMO EPS',
        'Brute Force 750 EPS',
        'Brute Force 750 EPS SE',
        'KEF',
        'KFX',
        'KFX 50',
        'KFX 90',
        'KSF',
        'KSV',
        'KVF',
        'Lakota',
        'MULE',
        'MULE PRO-FXT RANCH EDITION',
        'MULE PRO-FXT',
        'MULE PRO-FXT CAMO',
        'MULE PRO-FXT EPS',
        'MULE PRO-FXT EPS LE',
        'MULE PRO-FX RANCH EDITION',
        'MULE PRO-FXT EPS CAMO',
        'MULE PRO-FX EPS LE',
        'MULE PRO-FX EPS',
        'MULE PRO-DXT EPS',
        'MULE PRO-DX',
        'MULE 4010 Trans SE',
        'MULE 4010',
        'MULE SX XC SE',
        'MULE SX XC CAMO',
        'MULE SX XC',
        'MULE SX',
        'MULE 610 XC CAMO',
        'MULE 610 XC SE',
        'MULE 610',
        'TERYX',
        'TERYX EPS CAMO',
        'TERYX EPS LE',
        'TERYX EPS',
        'TERYX4',
        'TERYX4 EPS CAMO',
        'TERYX4 EPS LE',
        'TERYX4 EPS',
    ),
    'Kioti' => array(
        'MECHRON',
        'MECHRON 2200',
        'MECHRON 2200PS',
        'MECHRON 2240',
    ),
    'Kubota' => array(
        'RTV1140CPX',
    ),
    'Kymco' => array(
        'MONGOOSE',
        'MONGOOSE 70s',
        'MONGOOSE 90s',
        'MONGOOSE 270',
        'MAXXER 450i',
        'MXER',
        'MXU 150X',
        'MXU 270',
        'MXU 450i',
        'MXU 450i CAMO',
        'MXU 450i LE',
        'MXU500i',
        'MXU700i',
        'MXU700i LE EPS',
        'UXV 450i',
        'UXV 450i TURF',
        'UXV 450i CAMO',
        'UXV 450i LE',
        'UXV 500I',
        'UXV 700i',
        'UXV 700i TURF',
        'UXV 700i CAMO',
        'UXV 700i LE',
    ),
    'Polaris' => array(
        '250',
        '300',
        '400',
        '425',
        '450',
        '500',
        'ACE 500',
        'ACE 570',
        'ACE 570 SP',
        'ACE 900 XC',
        'ATP 330',
        'ATP 500',
        'BIG BOSS',
        'BRUTUS',
        'CREW',
        'CREW 570',
        'CREW 800',
        'CREW 900',
        'CYCLONE',
        'GENERAL 1000 EPS PREMIUM',
        'GENERAL 1000 EPS DELUXE',
        'GENERAL 4 1000 EPS',
        'GENERAL',
        'HAWKEYE',
        'HAWKEYE 300',
        'MAGNUM',
        'MAGNUM 325',
        'MAGNUM 330',
        'MAGNUM 425',
        'MAGNUM 500',
        'MXR 90',
        'MXR 450',
        'OUTLAW',
        'OUTLAW 50',
        'OUTLAW 90',
        'OUTLAW 450',
        'OUTLAW 500',
        'OUTLAW 525',
        'PHOENIX',
        'PHOENIX 200',
        'PHOENIX 250',
        'PHOENIX 500',
        'PREDATOR 90',
        'RANGER',
        'RANGER 400',
        'RANGER 500',
        'RANGER 570',
        'RANGER EV',
        'RANGER 570 EV LI-ION',
        'RANGER 570 FULL SIZR',
        'RANGER XP 900',
        'RANGER XP 1000',
        'RANGER DIESEL',
        'RANGER CREW 570-4',
        'RANGER CREW 570-6',
        'RANGER CREW XP 900',
        'RANGER CREW XP 100 EPS',
        'SAWTOOTH',
        'SAWTOOTH 200',
        'SCRAMBLER',
        'SCRAMBLER 90',
        'SCRAMBLER 400',
        'SCRAMBLER 500',
        'SCRAMBLER 850',
        'SCRAMBLER 1000',
        'SCRAMBLER XP 1000',
        'SPORTSMAN',
        'SPORTSMAN 400',
        'SPORTSMAN 450 H.O.',
        'SPORTSMAN 450 H.O. EPS',
        'SPORTSMAN 450 H.O. UTILITY EDITION',
        'SPORTSMAN 500',
        'SPORTSMAN 850',
        'SPORTSMAN 1000',
        'SPORTSMAN850 SP',
        'SPORTSMANXP 1000',
        'SPORTSMAN TPURING 570',
        'SPORTSMAN TPURING 570 EPS',
        'SPORTSMAN TPURING 570 EPS UTILITY EDITION',
        'SPORTSMAN TOURING 570 SP',
        'SPORTSMANTOURING X2 570 EPS',
        'SPORTSMANTOURING XP 1000',
        'SPORTSMAN TOURING X2 570 EPS',
        'SPORTSMAN BIG BOSS 6X6 570 EPS',
        'SPORTSMAN TOURING XP 1000',
        'SPORTSMAN 800',
        'SPORTSMAN 850 HIGH LIFTER',
        'SPORTSMAN XP 1000 HIGH LIFTER',
        'TRAIL BLAZER',
        'TRAIL BLAZER 250',
        'TRAIL BLAZER 330',
        'TRAIL BLAZER 400',
        'TRAIL BOSS 250',
        'TRAIL BLAZER 325',
        'RAZOR',
        'RAZOR RZR 570',
        'RAZOR RZR 570 EPS',
        'RAZOR RZR 900',
        'RAZOR RZR 900 EPS',
        'RAZOR RZR S 570',
        'RAZOR RZR S 900',
        'RAZOR RZR S 900 EPS',
        'RAZOR RZR S 1000 EPS',
        'RAZOR RZR XP 1000 EPS',
        'RAZOR RZR XP TURBO EPS',
        'RAZOR RZR 4 900 EPS',
        'RAZOR RZR XP 4 1000 EPS',
        'RAZOR RZR XP 4 TURBO EPS',
        'RAZOR RZR XP 1000 EPS VELOCITY BLUE',
        'RAZOR RZR XP 1000 EPS GOLD METALLIC',
        'RAZOR RZR XP 1000 EPS HIGH LIFTER EDITION',
        'RAZOR RZR XP 4 1000 EPS HIGH LIFTER EDITION',
        'XPEDITION',
        'XPEDITION 425',
        'XPLORER',
        'XPLORER 250',
        'XPLORER 300',
        'XPLORER 400',
        'XPLORER 500',
        'XPRESS 300',
        'XPRESS 400',
    ),
    'Suzuki' => array(
        'ALT50',
        'ALT50e TRAILBUDDY',
        'ALT125',
        'ALT185',
        'EIGER',
        'EIGER 300',
        'EIGER 350',
        'EIGER 400',
        'EIGER 500',
        'KINGQUAD',
        'KINGQUAD 750AXI CAMO',
        'KINGQUAD 750AXI SPECIAL EDITION',
        'KINGQUAD 750AXI',
        'KINGQUAD 500AXI CAMO',
        'KINGQUAD 500AXI SPECIAL EDITION',
        'KINGQUAD 500AXI',
        'KINGQUAD 400ASI CAMO',
        'KINGQUAD 400 ASI',
        'KINGQUAD 400 FSI',
        'LT',
        'LT125',
        'LT230',
        'LT250',
        'LT250R',
        'LT300',
        'LT400',
        'LT Z400',
        'LT500',
        'LT600',
        'QUADSPORT',
        'QUADSPORT Z50',
        'QUADSPORT Z90',
        'QUADSPORT Z250',
        'QUADSPORT Z400',
        'QUADMASTER 160',
        'QUADMASTER 250',
        'QUADMASTER 300',
        'QUADMASTER 400',
        'QUADMASTER 500',
        'OZARK 250',
    ),
    'Yamaha' => array(
        'BADGER',
        'BADGER 80',
        'BADGER 110',
        'BADGER 120',
        'BANSHEE',
        'BANSHEE250',
        'BANSHEE 350',
        'BANSHEE 400',
        'BANSHEE 450',
        'BANSHEE 500',
        'BANSHEE 550',
        'BANSHEE 600',
        'BANSHEE 650',
        'BANSHEE 700',
        'BANSHEE 750',
        'BANSHEE 800',
        'BEAR TRACKER',
        'BEAR TRACKER 250',
        'BEAR TRACKER 300',
        'BEAR TRACKER 350',
        'BEAR TRACKER 400',
        'BEAR TRACKER 450',
        'BEAR TRACKER 500',
        'BIG BEAR',
        'BIG BEAR250',
        'BIG BEAR 350',
        'BIG BEAR 400',
        'BIG BEAR 500',
        'BIG BEAR 550',
        'BIG BEAR 600',
        'BIG BEAR 660',
        'BIG BEAR 700',
        'BIG BEAR 750',
        'BIG BEAR 800',
        'BLASTER 50',
        'BLASTER 80',
        'BLASTER',
        'BLASTER 125',
        'BLASTER 200',
        'BLASTER 250',
        'BLASTER 300',
        'BLASTER 350',
        'BLASTER 400',
        'BLASTER 450',
        'BLASTER 500',
        'BREEZE 50',
        'BREEZE 80',
        'BREEZE',
        'BREEZE 125',
        'BREEZE 200',
        'BREEZE 250',
        'BREEZE 300',
        'BRUIN',
        'BRUIN 125',
        'BRUIN 250',
        'BRUIN 350',
        'BRUIN 400',
        'BRUIN 450',
        'BRUIN 500',
        'DRIVE',
        'GRIZZLY',
        'GRIZZLY EPS SE',
        'GRIZZLY EPS LE',
        'GRIZZLY EPS',
        'GRIZZLY 700 FI EPS S-LE',
        'GRIZZLY 700 FI EPS SE',
        'GRIZZLY 700 FI EPS SE 2',
        'GRIZZLY 700 FI EPS',
        'GRIZZLY 700 FI EPS CAMO',
        'GRIZZLY 700 FI',
        'KODIAK',
        'KODIAK 700 EPS SE',
        'KODIAK 700 EPS',
        'KODIAK 700',
        'RAPTOR 50',
        'RAPTOR 80',
        'RAPTOR',
        'RAPTOR 125',
        'RAPTOR 200',
        'RAPTOR 350',
        'RAPTOR 400',
        'RAPTOR 450',
        'RAPTOR 700R SE',
        'RAPTOR 700R',
        'RAPTOR 700',
        'RAPTOR 90',
        'RAPTOR YFZ50',
        'RHINO',
        'RHINO 450',
        'RHINO 500',
        'RHINO 550',
        'RHINO 600',
        'RHINO 660',
        'RHINO 700',
        'RHINO 800',
        'RHINO 900',
        'RHINO 1000',
        'TERRAPRO',
        'TERRAPRO 350',
        'TIMBERWOLF',
        'TIMBERWOLF 200',
        'TIMBERWOLF 300',
        'TIMBERWOLF 350',
        'VIKING',
        'VIKING EPS',
        'VIKING EPS SE',
        'VIKING VI EPS',
        'VIKING VI EPS SE',
        'VIKING WOLVERINE EPS',
        'VIKING WOLVERINE R-SPEC EPS CAMO',
        'VIKING WOLVERINE R-SPEC EPS',
        'VIKING WOLVERINE R-SPEC EPS SE',
        'WOLVERINE EPS',
        'WOLVERINE R-SPEC EPS CAMO',
        'WOLVERINE R- SPEC EPS',
        'WOLVERINE R- SPEC EPS (FOX)',
        'WOLVERINE R- SPEC EPS (KYB)',
        'WOLVERINE R-SPEC EPS SE',
        'YFZ50',
        'YFZ450R SE',
        'YFZ450R',
        'YXZ1000R-SS SE',
        'YXZ1000R-SS',
        'YXZ1000R',
        'YXZ1000R SE',
        'YXZ1000R SE 2',
        'ZINGER 50',
        'ZINGER 80',
    ),
);

return $models;