<?php

namespace cdemo;


$makes = array(
    'automobile' => array(
        'Acura',
        'Alfa Romeo',
        'AM General',
        'American Motors Corporation',
        'Auston Martin',
        'Audi',
        'Bentley',
        'BMW',
        'Buick',
        'Cadillac',
        'Chevrolet',
        'Chrysler',
        'Deawoo',
        'Daihatsu',
        'Datsun',
        'Dodge',
        'Eagle',
        'Ferrari',
        'Fiat',
        'Fisker',
        'Ford',
        'Freightliner',
        'Genesis',
        'Geo',
        'General Motors Corporation',
        'Honda',
        'Hummer',
        'Hyundai',
        'Infinity',
        'Isuzu',
        'Jaguar',
        'Jeep',
        'Kia',
        'Lamborghini',
        'Land Rover',
        'Lexus',
        'Lincoln',
        'Lotus',
        'Maserati',
        'Maybach',
        'Mazda',
        'McLaren',
        'Mercedes-Benz',
        'Mercury',
        'Mekur',
        'MINI',
        'Mitsubishi',
        'Nissan',
        'Oldsmobile',
        'Panoz',
        'Peugeot',
        'Plymouth',
        'Pontiac',
        'Porsche',
        'Ram',
        'Renault',
        'Rolls-Royce',
        'SAAB',
        'Saturn',
        'Scion',
        'Smart',
        'Spyker',
        'Sterling',
        'Subaru',
        'Suzuki',
        'Toyota',
        'Tesla',
        'Volkswagen',
        'Volvo',
        'Yugo',
    ),
    'motorcycle' => array(
        'Ducati',
        'Can-Am',
        'American IronHorse',
        'Aprilia',
        'Benelli',
        'Big Dog',
        'Bimota',
        'BMW',
        'Boss Horse',
        'Bourget\'s Bike Works',
        'BSA',
        'Buell',
        'Bultaco',
        'Desperado',
        'Harley-Davidson',
        'Hodaka',
        'Honda',
        'Husqvarna',
        'Hyosung',
        'Kawasaki',
        'KTM',
        'Moto Guzzi',
        'MV Agusta',
        'Norton',
        'Suzuki',
        'Titan Motorcycle Co.',
        'Triumph',
        'Ural',
        'Vento',
        'Victory',
        'Vincent',
        'Von Dutch Kustom Cycles',
        'Yamaha',
    ),
    'snowmobile' => array(
        'Arctic Cat',
        'Polaris',
        'Yamaha',
    ),
    'atv' => array(
        'Arctic Cat',
        'Bennche',
        'Bobcat',
        'Bombardier',
        'Can-Am / BRP',
        'Case IH',
        'CFMOTO',
        'Cub Cadet',
        'E-Ton',
        'Hisun',
        'Honda',
        'Hyosung',
        'John Deere',
        'Kawasaki',
        'Kioti',
        'Kubota',
        'Kymco',
        'Polaris',
        'Suzuki',
        'Yamaha',
    ),
);

return $makes;



